# @name AllCurrencies
GET http://localhost:8080/currency/all HTTP/1.1
Content-Type: application/json

###

# @name FindById
GET http://localhost:8080/currency/id/11 HTTP/1.1
Content-Type: application/json

###

# @name FindByCode
GET http://localhost:8080/currency/code/THB HTTP/1.1
Content-Type: application/json

###

# @name ConvertToCode
GET http://localhost:8080/currency/code HTTP/1.1
Content-Type: application/json

###

# @name Crypto
GET http://localhost:8080/crypto HTTP/1.1
Content-Type: application/json
